version: '3.3'

services:
  react_native:
    build:
      context: ../services/app/
      args:
        - NODE_ENV=development
    container_name: react_native_app
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
      - '19003:19003'
      - '19004:19004'
      - '19005:19005'
      - '19006:19006'
    volumes:  
      - ../services/app:/app
    healthcheck:
      disable: true
  
  backend:
      build:
        context: ../services/backend/
      container_name: node_backend
      ports:
        - '3000:3000'
      depends_on: 
        - db
      volumes:
        - '../services/backend:/app'
      
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - '../data/db:/data/db'

  mongo-express:
    image: mongo-express:latest
    depends_on: 
      - db 
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=db

  node-red:
    image: nodered/node-red
    environment:
      - TZ=Europe/Madrid
    ports:
      - '1880:1880'
    depends_on: 
      - db
    volumes:
      - '../services/node-red:/data'
    # webserver:
    #   image: nginx
    #   depends_on: 
    #     - mongo-express
    #   ports:
    #     - '80:80'
    #   volumes:
    #     - ./nginx:/etc/nginx/conf.d
    #     - ./data/public:/data
          