version: '3.3'

services:
  app:
    build:
      context: ../services/app/
      args:
        - NODE_ENV=development
    container_name: app
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
      - '19003:19003'
      - '19004:19004'
      - '19005:19005'
      - '19006:19006'
    volumes:  
      - ../services/app:/app
    healthcheck:
      disable: true
           
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - '../data/db:/data/db'

  mongo-express:
    image: mongo-express:latest
    depends_on: 
      - db 
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=db

  node-red:
    image: nodered/node-red
    environment:
      - TZ=Europe/Madrid
    ports:
      - '1880:1880'
    depends_on: 
      - db
    volumes:
      - '../services/node-red:/data'

  webserver:
    container_name: "webserver"
    image: nginx
    depends_on: 
      - mongo-express
      - app
      - node-red
      - db
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
          